clear;
clc;
close all;
%set the env
simTime = 135;
scene = uavScenario(ReferenceLocation=[47.507014314851375, 19.04718380067424 0], ...
    UpdateRate=2,StopTime=simTime);
xTerrainLimits = [-200 200];
yTerrainLimits = [-200 200];
addMesh(scene,"terrain",{'gmted2010',xTerrainLimits,yTerrainLimits},[0.6,0.6,0.6]);
xBuildingLimits = [-150 150];
yBuildingLimits = [-150 150];
addMesh(scene,"buildings",{"Geo_data/budapest.osm",xBuildingLimits,yBuildingLimits,"auto"},[0.6431,0.8706,0.6275]);
groundHeight = terrainHeight(scene,0,0);
fprintf("Ground H: %.2f m \n",groundHeight);


%map the fl
mappingAltitude = groundHeight + 70;
mappingWaypoints = [
    -120 -120 mappingAltitude
    120 -120 mappingAltitude
    120 -60 mappingAltitude
    -120 -60 mappingAltitude
    -120 0 mappingAltitude
    120 0 mappingAltitude
    120 60 mappingAltitude
    -120 60 mappingAltitude
    -120 120 mappingAltitude
    120 120 mappingAltitude
    ];
mappingTime = 0 : 15 : 135;

%traj
orientation = quaternion([0 0 0],"eulerd","ZYX","frame");
orientations = repmat(orientation,10,1);
mappingTrajectory = waypointTrajectory( ...
    "Waypoints",mappingWaypoints, ...
    "Orientation",orientations, ...
    "TimeOfArrival",mappingTime, ...
    "SampleRate",2, ...
    "ReferenceFrame","ENU");
%uav
mappingUAV = uavPlatform( ...
    "MappingUAV", ...
    scene, ...
    "Trajectory",mappingTrajectory, ...
    "ReferenceFrame","ENU");

updateMesh( ...
    mappingUAV, ...
    "quadrotor", ...
    {8}, ...
    [1 0 0], ...
    eye(4));
%% Add LiDAR

lidarModel = uavLidarPointCloudGenerator( ...
    "AzimuthResolution",0.6, ...
    "ElevationLimits",[-90 -20], ...
    "ElevationResolution",2.5, ...
    "MaxRange",200, ...
    "UpdateRate",2, ...
    "HasOrganizedOutput",true);

lidar = uavSensor( ...
    "Lidar", ...
    mappingUAV, ...
    lidarModel, ...
    "MountingLocation",[0 0 -1], ...
    "MountingAngles",[0 0 0]);

%% Create empty 3D occupancy map

map3D = occupancyMap3D(1);
figure;

[ax,plotFrames] = show3D(scene);

xlim(ax,[-200 200]);
ylim(ax,[-200 200]);
zlim(ax,[140 250]);

view(ax,[-45 30]);
axis(ax,"equal");

setup(scene);

while scene.IsRunning

    % Read latest LiDAR scan
    [isUpdated,lidarTime,ptCloud] = read(lidar);

    if isUpdated

        % Get LiDAR pose in the ENU world frame
        sensorPose = getTransform( ...
            scene.TransformTree, ...
            "ENU", ...
            "MappingUAV/Lidar", ...
            lidarTime);

        % Remove invalid LiDAR points
        validCloud = removeInvalidPoints(ptCloud);

        % Add scan to occupancy map
        insertPointCloud( ...
            map3D, ...
            [sensorPose(1:3,4)' tform2quat(sensorPose)], ...
            validCloud, ...
            500);
    end

    % Advance UAV
    advance(scene);

    % Generate new sensor data
    updateSensors(scene);

end
%% Show generated occupancy map

inflate(map3D,3);
figure;

show(map3D);

axis equal;
view([-45 30]);

title("3D Occupancy Map");
%% RRT* path planning

ss = stateSpaceSE3([
    -180 180
    -180 180
    groundHeight+10 groundHeight+80
    inf inf
    inf inf
    inf inf
    inf inf
    ]);

sv = validatorOccupancyMap3D( ...
    ss, ...
    Map=map3D, ...
    ValidationDistance=0.5);
planner = plannerRRTStar( ...
    ss, ...
    sv, ...
    MaxConnectionDistance=60, ...
    MaxIterations=3000, ...
    GoalReachedFcn=@(~,s,g)(norm(s(1:3)-g(1:3)) < 3), ...
    GoalBias=0.1);
start = [-80 -80 groundHeight+40 1 0 0 0];
goal  = [100  80 groundHeight+40 1 0 0 0];
%% Check start and goal

startValid = isStateValid(sv,start)
goalValid = isStateValid(sv,goal)

%% Plan collision-free path ???

rng(1,"twister");

[pathObj,solutionInfo] = plan(planner,start,goal);

%% Show planned path

figure;

show(map3D);
axis equal;
view([-45 30]);
hold on;

% Start
scatter3( ...
    start(1), ...
    start(2), ...
    start(3), ...
    80, ...
    "g", ...
    "filled");

% Goal
scatter3( ...
    goal(1), ...
    goal(2), ...
    goal(3), ...
    80, ...
    "r", ...
    "filled");

% RRT* path
plot3( ...
    pathObj.States(:,1), ...
    pathObj.States(:,2), ...
    pathObj.States(:,3), ...
    "r-", ...
    LineWidth=3);

title("RRT* Autonomous Path Through Area");

hold off;

%% Connect uav to Fly the RRT* generated path

% Extract XYZ positions generated by RRT*
plannedWaypoints = pathObj.States(:,1:3);

disp("Automatically generated waypoints:");
disp(plannedWaypoints);

% Desired UAV speed
cruiseSpeed = 8; % m/s

% Calculate distance of every path segment
segmentDistances = vecnorm(diff(plannedWaypoints),2,2);

% Calculate travel time for each segment
segmentTimes = segmentDistances / cruiseSpeed;

% Arrival time at every waypoint
plannedTime = [0; cumsum(segmentTimes)];

fprintf("Autonomous flight duration: %.2f seconds\n",plannedTime(end));

%% Convert RRT* path into UAV trajectory

plannedTrajectory = waypointTrajectory( ...
    "Waypoints",plannedWaypoints, ...
    "TimeOfArrival",plannedTime, ...
    "SampleRate",2, ...
    "ReferenceFrame","ENU");
%resetting
restart(scene);

figure;
flightAx = show3D(scene);

axis(flightAx,"equal");
view(flightAx,[-45 30]);

xlim(flightAx,[-200 200]);
ylim(flightAx,[-200 200]);
zlim(flightAx,[140 250]);

hold(flightAx,"on");

% Show RRT* path
plot3( ...
    flightAx, ...
    plannedWaypoints(:,1), ...
    plannedWaypoints(:,2), ...
    plannedWaypoints(:,3), ...
    "r-", ...
    LineWidth=3);

% Start
scatter3( ...
    flightAx, ...
    start(1),start(2),start(3), ...
    80,"g","filled");

% Goal
scatter3( ...
    flightAx, ...
    goal(1),goal(2),goal(3), ...
    80,"r","filled");

title(flightAx,"Autonomous RRT* UAV Flight");

hold(flightAx,"off");

%% Execute planned trajectory using SAME mappingUAV

setup(scene);

while scene.IsRunning && scene.CurrentTime <= plannedTime(end)

    % Get RRT* trajectory state at current time
    [position,orientation,velocity,acceleration,angularVelocity] = ...
        lookupPose(plannedTrajectory,scene.CurrentTime);

    % Convert quaternion object to [qw qx qy qz]
    q = compact(orientation);

    % uavPlatform.move requires:
    % [position velocity acceleration quaternion angularVelocity]
    motion = [ ...
        position ...
        velocity ...
        acceleration ...
        q ...
        angularVelocity];

    % Move the SAME UAV
    move(mappingUAV,motion);

    % Update visualization
    show3D( ...
        scene, ...
        "Time",scene.CurrentTime, ...
        Parent=flightAx, ...
        FastUpdate=true);

    drawnow;

    pause(1/scene.UpdateRate);

    % Advance simulation time
    advance(scene);
end