clear;
clc;
close all;

%% Create Budapest scenario
scene = Create_Scenario_Cuboid();

%% Define UAV route
% NED coordinates: [North, East, Down]
waypoints = [
    -168.737, 209.485, -200;
    -168.749, -95.8888, -200;
     142.827, 206.568, -200;
     124.595, -97.0444, -200;
    -168.737, 209.485, -200;
];

toa = [0 40 80 120 160];

%% Create trajectory
trajectory = waypointTrajectory( ...
    waypoints, ...
    'TimeOfArrival', toa, ...
    'SampleRate', 1, ...
    'ReferenceFrame', 'NED');

%% Create UAV platform
plat = uavPlatform( ...
    "UAV", ...
    scene, ...
    'Trajectory', trajectory, ...
    'ReferenceFrame', 'NED');

%% Add UAV mesh
updateMesh( ...
    plat, ...
    "quadrotor", ...
    {10}, ...
    [1 0 0], ...
    [0 0 0], ...
    eul2quat([0 0 pi]));

%% Create lidar model
lidarModel = uavLidarPointCloudGenerator( ...
    'AzimuthResolution', 3, ...
    'ElevationLimits', [-20 20], ...
    'ElevationResolution', 4, ...
    'MaxRange', 200, ...
    'UpdateRate', 0.5, ...
    'HasNoise', false, ...
    'HasOrganizedOutput', false);

%% Mount lidar on UAV
lidar = uavSensor( ...
    "Lidar", ...
    plat, ...
    lidarModel, ...
    'MountingLocation', [0 0 2]);

%% Prepare scenario
setup(scene);

%% Create 3D visualization
[figAxis, plotFrames] = show3D(scene);

view(figAxis, 45, 30);
axis(figAxis, "equal");

%% Convert route from NED to ENU for plotting
% NED: [North, East, Down]
% ENU: [East, North, Up]
waypointsENU = [
    waypoints(:,2), ...
    waypoints(:,1), ...
   -waypoints(:,3)
];

hold(figAxis, "on");

plot3( ...
    figAxis, ...
    waypointsENU(:,1), ...
    waypointsENU(:,2), ...
    waypointsENU(:,3), ...
    "-o", ...
    'LineWidth', 1.5);

%% Create lidar point-cloud plot
lidarPlot = scatter3( ...
    NaN, ...
    NaN, ...
    NaN, ...
    1, ...
    [1 0 0], ...
    ".", ...
    'Parent', plotFrames.UAV.Lidar);
    uavMarker = scatter3( ...
    0, 0, 0, ...
    120, ...
    [1 1 0], ...
    "filled", ...
    "Marker", "diamond", ...
    "Parent", plotFrames.UAV.Lidar);

figHandle = ancestor(figAxis, "figure");

hold(figAxis, "off");

%% Run simulation
while isgraphics(figHandle) && advance(scene)

    updateSensors(scene);
    [isUpdated, ~, pointCloudData] = read(lidar);

    % The window may have been closed during advance
    if ~isgraphics(figHandle)
        break;
    end

    show3D( ...
        scene, ...
        "Parent", figAxis, ...
        "FastUpdate", true);

    if isUpdated
        points = pointCloudData.Location;

        % Remove rays that did not hit a surface
        validPoints = points(all(isfinite(points), 2), :);

        lidarPlot.XData = validPoints(:,1);
        lidarPlot.YData = validPoints(:,2);
        lidarPlot.ZData = validPoints(:,3);
    end

    drawnow limitrate;
    pause(0.02);
end